//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/InputForMediator.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputForMediator : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputForMediator()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputForMediator"",
    ""maps"": [
        {
            ""name"": ""Get"",
            ""id"": ""9bb501ff-a972-4927-be9a-b7fb0a664cf1"",
            ""actions"": [
                {
                    ""name"": ""Health"",
                    ""type"": ""Button"",
                    ""id"": ""5f0e0f59-0086-4d9e-b155-0953e670f20f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Expierence"",
                    ""type"": ""Button"",
                    ""id"": ""6ce03871-314c-40c3-9aef-e82e3228cea2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""82b2e419-8560-4daa-9874-cdd06fd57fbc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""527e50b2-1a95-48ff-9d44-329988e280f9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Expierence"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Get
        m_Get = asset.FindActionMap("Get", throwIfNotFound: true);
        m_Get_Health = m_Get.FindAction("Health", throwIfNotFound: true);
        m_Get_Expierence = m_Get.FindAction("Expierence", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Get
    private readonly InputActionMap m_Get;
    private IGetActions m_GetActionsCallbackInterface;
    private readonly InputAction m_Get_Health;
    private readonly InputAction m_Get_Expierence;
    public struct GetActions
    {
        private @InputForMediator m_Wrapper;
        public GetActions(@InputForMediator wrapper) { m_Wrapper = wrapper; }
        public InputAction @Health => m_Wrapper.m_Get_Health;
        public InputAction @Expierence => m_Wrapper.m_Get_Expierence;
        public InputActionMap Get() { return m_Wrapper.m_Get; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GetActions set) { return set.Get(); }
        public void SetCallbacks(IGetActions instance)
        {
            if (m_Wrapper.m_GetActionsCallbackInterface != null)
            {
                @Health.started -= m_Wrapper.m_GetActionsCallbackInterface.OnHealth;
                @Health.performed -= m_Wrapper.m_GetActionsCallbackInterface.OnHealth;
                @Health.canceled -= m_Wrapper.m_GetActionsCallbackInterface.OnHealth;
                @Expierence.started -= m_Wrapper.m_GetActionsCallbackInterface.OnExpierence;
                @Expierence.performed -= m_Wrapper.m_GetActionsCallbackInterface.OnExpierence;
                @Expierence.canceled -= m_Wrapper.m_GetActionsCallbackInterface.OnExpierence;
            }
            m_Wrapper.m_GetActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Health.started += instance.OnHealth;
                @Health.performed += instance.OnHealth;
                @Health.canceled += instance.OnHealth;
                @Expierence.started += instance.OnExpierence;
                @Expierence.performed += instance.OnExpierence;
                @Expierence.canceled += instance.OnExpierence;
            }
        }
    }
    public GetActions @Get => new GetActions(this);
    public interface IGetActions
    {
        void OnHealth(InputAction.CallbackContext context);
        void OnExpierence(InputAction.CallbackContext context);
    }
}
